### ISSUE TITLE
ChronoMeter Alarm Bug

### ISSUE THREAD

**Issue by Faunsce** [raiguard/ModernGadgets#141] opened 2019-03-21 12:53 UTC
When trying to set custom alarms for usage in chronometer using the setting page, the "\" character is consistently removed upon every entry, breaking the path to the wav. Manually adding through the .ini fixes this, however no personal .wav's of mine would be read. only the deafult windows alarms provided by the default settings of chronometer.

**Comment by raiguard** [comment] 2019-03-22 00:34
Huh, it works just fine for me. What is the file path (including the username, if you're comfortable with that) that you're trying to use?

**Comment by Faunsce** [comment] 2019-03-22 04:35
its C:\Windows\Media\Alarm01.wav is the default and the custom I tried was C:\ and H:\ also C:\Users\Domin\Desktop is all I tried. Domin was supposed to be domain but I misspelled. don't even remember why I wanted it to be the domain.

**Comment by raiguard** [comment] 2019-03-22 09:56
Ohhhh lol, I thought you were talking about quotation marks, not backslashes. The backslash that you wrote in the post doesn't actually show up.

I was able to reproduce the issue, and I'll find a way to fix it. Hopefully.

**Comment by Faunsce** [comment] 2019-03-22 21:12
Thanks for looking into it, great work overall though, love the plugin!

**Comment by raiguard** [comment] 2019-04-01 14:22
Thanks for the report, this is now fixed for v1.5.1.

**Comment by raiguard** [comment] 2019-04-05 02:54
v1.5.1-rc.1 is out. Please update and let me know if the issue is fixed for you!

**Comment by raiguard** [comment] 2019-04-13 15:55
Well, I am confident that this is fixed, so I'm closing this issue. :)

**Closed by raiguard** 2019-04-13 15:55 UTC
Labels: bug
