### ISSUE TITLE
Division by 0 in the log

### ISSUE THREAD

**Issue by SerVB** [raiguard/ModernGadgets#133] opened 2019-02-06 14:30 UTC
Hi! I've just checked the log and it shows this:
![image](https://user-images.githubusercontent.com/20105593/52348147-ac5db880-2a34-11e9-8a76-45f962fc3c22.png)

Actually, everything works but these messages are a bit confusing :)

I use `v1.5.0-beta.8`.

**Comment by raiguard** [comment] 2019-02-12 00:48
What is your Max CPU Temperature setting set to? Is it on auto or manual?

**Comment by SerVB** [comment] 2019-02-12 14:50
Auto:
![image](https://user-images.githubusercontent.com/20105593/52643371-ec69e300-2eed-11e9-8b4f-f0cb25787626.png)

When I change it to "override, 100", no errors are produced.

Sorry, I was wrong about the version (I guess it was `beta.2`). I've just updated to real `v1.5.0-beta.8`. The ScaleX is now different:
![image](https://user-images.githubusercontent.com/20105593/52643517-41a5f480-2eee-11e9-8b26-b88785f9c092.png)

**Comment by raiguard** [comment] 2019-02-13 03:54
Aha, this was indeed a bug. The problem was that since you didn't install and configure HWiNFO, there was no CPU temperature reading. Therefore, the maximum CPU temperature was zero, so it was dividing by zero. I simply added a formula to make the minimum possible value be 1. This should fix your issue.

**Comment by raiguard** [comment] 2019-02-13 03:56
Fixed in v1.5.0-beta.9.

**Comment by SerVB** [comment] 2019-02-13 12:11
> Fixed in v1.5.0-beta.9.
How to download and check? There is no such release yet...

> The problem was that since you didn't install and configure HWiNFO
The right phrase here is `I didn't install OR configure HWiNFO`. Actually, I have it installed. However, I think my Ryzen 2600X doesn't have any temperature sensors available in HWiNFO so I've left default settings in SMV.

**Comment by Shrekmachine** [comment] 2019-02-13 12:46
It has, but only one. Here from my system with an 2700x with the Aorus Ultra Board.

I assigend the value to all Cores



Cheers Frédéric

**Comment by SerVB** [comment] 2019-02-13 13:03
@Shrekmachine, thanks for the idea.

Offtopic: could you also show screenshots of CPU Meter and CPU Settings skins?

**Comment by raiguard** [comment] 2019-02-13 13:09
Ah, you're also suffering from another bug (#128) that will be fixed in v1.5.0-beta.9: If you didn't configure your Core 0 temperature sensor then it wouldn't let you select any of the HWiNFO-related options.

I'm going to release beta 9 probably sometime today (MST).

**Comment by SerVB** [comment] 2019-02-13 13:26
> I'm going to release beta 9 probably sometime today (MST).

Okay :) I do not hurry you.

By the way, my issue is a duplicate of #119...

**Comment by Shrekmachine** [comment] 2019-02-13 13:38
<img width="328" alt="2019-02-13_14h36_27" src="https://user-images.githubusercontent.com/8019511/52715511-ebdc5580-2f9c-11e9-9eb1-8545526b0072.png">

**Comment by raiguard** [comment] 2019-02-13 14:28
Ah! I didn't actually fix the issue before closing it!? That was silly of me. :/

**Comment by raiguard** [comment] 2019-02-15 03:53
Beta 9 is finally out, sorry for the delay. Let me know if the issue's been fixed!

**Comment by Shrekmachine** [comment] 2019-02-15 08:40
No errors in my log in the last 1h

**Comment by SerVB** [comment] 2019-02-15 08:48
Can check only in two days, sorry.

**Comment by raiguard** [comment] 2019-02-15 13:39
Ok. I'm pretty sure this is fixed so I'm going to close it. If it's still broken when you are able to test, let me know and I'll see what I can do (and reopen the issue, of course!)

**Closed by raiguard** 2019-02-15 13:39 UTC
Labels: bug

**Comment by SerVB** [comment] 2019-02-16 12:04
I've just checked. No errors in log.

By the way, is it okay that temperature settings changes require to refresh cpu meter skin to apply them?

**Comment by raiguard** [comment] 2019-02-16 17:26
Yes that is normal. The HWiNFO tutorial states that you need to click the blue refresh button above the SMV button once you're done. That's the same thing as refreshing.

Anyway, glad that the issue is fixed now!
