### ISSUE TITLE
CPU Meter - Page File not updating

### ISSUE THREAD

**Issue by Shrekmachine** [raiguard/ModernGadgets#152] opened 2019-04-26 11:39 UTC
max Page file number is not updating until you jump into confguration once. Interstingly the bar is working correctly.
In my case max PageFile was stuck at 2GB, jumping to 29GB after jumping into config panel

**Comment by raiguard** [comment] 2019-04-30 23:46
Oops, this was my bad. I neglected to make the total page file size update regularly, it was only setting itself when the gadget was fully refreshed. Should be fixed in v1.5.1-rc.4.

**Comment by raiguard** [comment] 2019-05-01 00:00
Released. Could you confirm that the bug is fixed in v1.5.1-rc.4?

**Comment by raiguard** [comment] 2019-05-03 19:32
Are you able to reproduce it in v1.5.1-rc.4? If not I'm going to officially release v1.5.1.

**Comment by Shrekmachine** [comment] 2019-05-03 21:35
I had no chance to try it yet :/

**Comment by raiguard** [comment] 2019-05-03 23:05
Ok, let me know when you do. I'm fairly confident that it's fixed, so I'm going to release v1.5.1 officially. If it turns out that my fix was incorrect, then I'll just release a v1.5.2 once we figure out the actual issue. Thanks!

**Comment by raiguard** [comment] 2019-05-04 04:48
v1.5.1 is out, closing this issue. If you run into it again please let me know!

**Closed by raiguard** 2019-05-04 04:48 UTC
Labels: bug
