### ISSUE TITLE
Event timer - entering correct timer

### ISSUE THREAD

**Issue by Shrekmachine** [raiguard/ModernGadgets#155] opened 2019-05-19 07:27 UTC
is a little challenge as it a very specific (technical) format.
How about, if date is enough to accept the input or prefill if empty with an example?

**Comment by raiguard** [comment] 2019-05-19 17:33
I have been thinking about redoing that interface, but don't know how I would go about it. It's in the cards.

**Comment by Shrekmachine** [comment] 2019-05-21 06:33
for now it would be enough for me to deal with the field itself :) 
see suggestion in 1st comment

**Comment by raiguard** [comment] 2019-08-28 23:53
I am not going to have time to do anything about this before I run out of time, so I'm going to close it.

Although I also have to ask: Shrekmachine, you seem pretty active on here and interested in ModernGadgets. Would you be willing to "maintain" the repository while I am gone? In case I haven't told you yet, in three weeks I will be leaving to become a missionary for my religion, during which time I will have very limited internet access. I won't be able to directly manage this repository during the span of my calling. I have already asked SilverAzide, the guy to got me into Rainmeter, if he could maintain the project itself (basically just fix any bugs that are caused by Rainmeter updates, if any). However, I need someone to maintain this repository.

All it would entail is answering any questions that you can, adding labels to and closing issues where appropriate. Should only take as much time as there are issues that are created.

Would you be willing?

**Closed by raiguard** 2019-08-28 23:53 UTC
Labels: feedback
