### ISSUE TITLE
[Diskmeter] ImageName: Unable to open warning.png

### ISSUE THREAD

**Issue by unknownsoldierx** [raiguard/ModernGadgets#244] opened 2021-08-27 07:12 UTC
Rainmeter shows this in the log every second.

`ImageName: Unable to open: D:\Documents\Rainmeter\Skins\ModernGadgets\@Resources\Assets\Images\warning.png (ModernGadgets\DisksMeter\DisksMeter.ini)`

**Comment by Tweekme** [comment] 2021-09-12 03:34
I have this same issue after updating a working suite of Rainmeter/ HWiNFO64/ ModernGadgets. I only have two internal hard drives. I tried adding the warning.png file (there was no /Assets/Images folder, so I created them). This did not solve my issue. All other skins work until I try and activate the Disks Meter, then Rainmeter freezes and quits. It cannot be relaunched. The only fix is to reinstall ModernGadgets and setup skins again without adding Disks Meter.
I am using ModernGadgets_1.7.0, hwi_710, Rainmeter-4.5.1
Please help! Thank you.

**Comment by unknownsoldierx** [comment] 2021-09-12 04:35
Same issue here with DisksMeter.

DisksMeter can be removed without reinstalling or reconfiguring ModernGadgets.

C:\Users\username\AppData\Roaming\Rainmeter\Rainmeter.ini

Remove the [ModernGadgets\DisksMeter] settings, save the file and launch Rainmeter.

**Comment by Tweekme** [comment] 2021-09-12 04:44
> Same issue here with DisksMeter.
> 
> DisksMeter can be disabled without reinstalling or reconfiguring ModernGadgets.
> 
> C:\Users\username\AppData\Roaming\Rainmeter\Rainmeter.ini
> 
> Remove the [ModernGadgets\DisksMeter] settings, save the file and launch Rainmeter.

Thanks for the reply. I do have it disabled currently and all other gadgets work perfect. I would like to get Disks Meter going again though. Have you found a solution? Thank you!

**Comment by SilverAzide** [comment] 2021-09-12 05:28
@Tweekme, @unknownsoldierx,
The Disks Meter crashing issue you are referring to has nothing to do with the missing warning.png file.  See issue #247.  It is caused by a bug in Rainmeter 4.5.1.

**Comment by Tweekme** [comment] 2021-09-12 15:28
Thank you @SilverAzide . This indeed fixed the issue!

**Comment by raiguard** [comment] 2021-09-13 01:34
This was fixed in 35e88fd8 for the next version.

**Closed** 2021-09-13 02:01 UTC
Labels: bug
