### ISSUE TITLE
Text flowing off screen and lots of inscrutable icons

### ISSUE THREAD

**Issue by aniforprez** [raiguard/ModernGadgets#59] opened 2017-12-28 11:23 UTC
After the 1.3.0-beta.1 update, every settings widget now looks like this

![](https://i.gyazo.com/51a0972176d974a16296f4c44e3845e2.png)

![](https://i.gyazo.com/70df6e9ac616e32f62fb6911634b8001.png)

![](https://i.gyazo.com/4aee7acc2f29f7eb62f345a2e7ae90fb.png)

Keep up the excellent work on the gadgets!

**Comment by raiguard** [comment] 2017-12-28 17:41
Try resetting to defaults and see if that fixes it. Also, could you go into @Resources/Fonts and make sure Elegant Icons is there? Either Elegant Icons is missing, or the buttons aren't using it for some reason.

**Comment by raiguard** [comment] 2017-12-28 17:42
![2017-12-28 10_41_51-](https://user-images.githubusercontent.com/3515394/34418512-c0f626c8-ebbb-11e7-983a-7de84960b681.png)
This is what it should look like.

**Comment by aniforprez** [comment] 2017-12-29 07:32
Yes which is why I was extremely puzzled with the other weird icons. So just to clarify, is this a bug you can fix or I should do something to fix it on my end?

**Comment by raiguard** [comment] 2017-12-29 07:33
So you’re saying that the variables are there?

**Comment by aniforprez** [comment] 2017-12-29 07:34
No I'm saying I have no idea where to look for these variables 😋

**Comment by aniforprez** [comment] 2017-12-29 07:37
Ok I looked for "StyleSheet" in the file explorer and found the file and the variables are there.

```
toggleOn=[\x5a]
toggleOff=[\x56]
```

**Comment by raiguard** [comment] 2017-12-29 07:54
The folder you need to look in is the “MG Skins folder” that you can access through the gadget manager. It’s in ‘@Resources/Settings’.

Go to ‘@Resources/Fonts’ and let me know if elegant icons is in there. Also, what Rainmeter version are you on?

**Comment by aniforprez** [comment] 2017-12-29 08:36
As I said in my last comment, I was able to find the file and confirm that the variables are in the file.

There's an "ElegantIcons.ttf" file in "Resources/Fonts" which I assume is Elegant Icons? If so it's there.

I'm using Rainmeter 4.1.0 beta r2873 64-bit

**Comment by aniforprez** [comment] 2017-12-29 08:38
Oh hey! I upgraded Rainmeter to 4.2.0 beta r3018 and the issue is solved! Is there some new API that you're using?

**Comment by raiguard** [comment] 2017-12-29 16:15
Huh, I thought they were 4.1 as well, that was the intention. I’ll downgrade back to it and fix the issues. Thanks for the report!

**Comment by raiguard** [comment] 2017-12-29 21:25
So I've figured it out. The beta you were on had an issue with parsing inline variables in some instances. The bug was fixed in the next beta, and was the cause of the toggle buttons being weird (rainmeter wasn't parsing the variable as a variable). On the final 4.1 release, it works just fine.

**Closed by raiguard** 2017-12-29 21:25 UTC
Labels: bug, support
