### ISSUE TITLE
[Disk Meter] Loading the Disk Meter skin will cause the newest version of Rainmeter (V4.5.1) to crash

### ISSUE THREAD

**Issue by Yangster2000** [raiguard/ModernGadgets#247] opened 2021-09-12 01:01 UTC
As per title.

Rainmeter log file shows nothing useful.

**Comment by Yangster2000** [comment] 2021-09-12 01:08
![Untitled](https://user-images.githubusercontent.com/49379298/132967371-7d1ee16c-a305-416f-aec3-fc9facf69107.png)

**Comment by SilverAzide** [comment] 2021-09-12 02:43
The Rainmeter developers are looking into it.  There seems to be some odd interaction with this particular skin and the new changes to the SysInfo measure.  If you need a quick fix and don't want to revert to the previous version of Rainmeter, you can replace the following measure in the DiskMeter.ini file:

```ini
[MeasureUserName]
Measure=String
String=%USER_NAME%
IfCondition=1
IfTrueAction=[!CommandMeasure MeasureGetLocalGroup "Run"]
```
Look for a new version of Rainmeter to correct this issue; the problem is not really this skin.

**Comment by raiguard** [comment] 2021-09-12 04:42
Thanks as always for staying on top of things SA. I'm going to do some ModernGadgets dev once I get a Windows VM set up on my machine and figure out how to sync certain directories between the VM and my actual disk (so I can do the editing in my preferred editor, which is unix-only).

**Comment by SilverAzide** [comment] 2021-09-12 05:32
> Thanks as always for staying on top of things SA. I'm going to do some ModernGadgets dev once I get a Windows VM set up on my machine and figure out how to sync certain directories between the VM and my actual disk (so I can do the editing in my preferred editor, which is unix-only).

You're welcome!  You mean Notepad++ doesn't run in Unix?  😱  /jk!

**Comment by raiguard** [comment] 2021-09-12 05:35
Lol, my editor is [kakoune](https://github.com/mawww/kakoune), but I digress. :P

**Comment by SilverAzide** [comment] 2021-09-12 15:09
Rainmeter 4.5.2 is out and fixes this issue.

**Comment by Tweekme** [comment] 2021-09-12 15:27
Excellent! This fixes the issue. Thank you for the speedy fix!

**Comment by raiguard** [comment] 2021-09-12 19:50
![image](https://user-images.githubusercontent.com/3515394/133000821-93fa980d-97f7-436c-8fa2-f7c1b2cc1aa8.png)

Let's do this.

Closing issue after upstream fix.

**Closed by raiguard** 2021-09-12 19:50 UTC
Labels: bug, upstream
