### ISSUE TITLE
Clipboard Meter breaks on system start-up

### ISSUE THREAD

**Issue by Darkened5ky** [raiguard/ModernGadgets#176] opened 2019-10-22 18:43 UTC
Occasionally when I log into windows after a fresh start of my machine, I will get this error.

![image](https://user-images.githubusercontent.com/39975546/67318668-06ba7e80-f4c9-11e9-919a-075a6cae6503.png)

It doesn't seem to have any specific trigger. It will sometimes happen and sometimes not. Here is a [pastebin](https://pastebin.com/y87428tb) link to the info that clicking "Details" gives.

**Comment by SilverAzide** [comment] 2019-10-22 22:07
Any chance you have another app running on startup that monitors the clipboard?  One example is the Windows Remote Desktop utility, or a virtual machine (Hyper-V, VirtualBox, etc.).  It also could be a support app provided by your PC vendor.  If you look at processes in Task Manager, do you see rdpclip.exe?  Where I'm going with this is that this error can happen when two apps are "fighting" to access the clipboard at the same time.

**Comment by Darkened5ky** [comment] 2019-10-24 23:11
Hmm, I do have greenshot which has access to the clipboard. I'll do some testing and see what I can find.

**Comment by pr0vieh** [comment] 2019-10-25 16:38
i have the same problem and Disabling ClipboardMonitor and the msg is gone away!
i have installed VisualStudio and some .NET Debugging stuff i think this brings out the error
usually the error swallowed?

**Comment by SilverAzide** [comment] 2019-10-26 01:25
OK, good to know!  The clipboard plugin is a third-party plugin and the author does not appear to be active, so there is nothing that can be done to fix it.  I have Visual Studio as well and I am not getting any error like this, but I will keep investigating.

**Comment by raiguard** [comment] 2019-11-10 22:10
I can consistently reproduce this if Windows loads the user before I log in (e.g. I log into my user, then restart and wait a little bit). When I log in, the error is there 100% of the time.

**Comment by raiguard** [comment] 2020-03-26 17:58
Since this would require a complete plugin rewrite that is beyond my abilities, I'm closing this. I'll create a `known issues` list somewhere and add this to it.

**Closed by raiguard** 2020-03-26 17:58 UTC
Labels: bug
