### ISSUE TITLE
HWiNFO Shared Memory Viewer - Problem

### ISSUE THREAD

**Issue by Minischatten** [raiguard/ModernGadgets#193] opened 2020-02-24 16:05 UTC
Hello,
have a small problem with the scaling of HWiNFO Shared Memory Viewer. It cannot be scaled. So it is impossible to change settings. I think it might be a problem with my 4k monitor, but I am not sure.

Do you have an idea?

Sorry for my bad english, but I hope you can understand it anyway :)
<img width="480" alt="2020-02-24" src="https://user-images.githubusercontent.com/61423557/75168787-c180b480-5727-11ea-9c01-1868eb6bd5c7.png">

**Comment by raiguard** [comment] 2020-02-24 16:14
This is a known problem that is hard to reproduce. To fix it, set your display scale to 1.0, then re-open the window. Configure your settings, close it, then you can set your display scale back to whatever it was.

**Comment by Minischatten** [comment] 2020-02-24 17:19
Perfect, thank you, that worked. It's horrible and you need a magnifying glass but it works :)

**Comment by raiguard** [comment] 2020-02-24 17:20
Yeah, the SMV is nice, but it's also still a bit of a mess. I asked the plugin author to make it because there was no good way to make scroll panes or dynamic content with Rainmeter. Now there is, so someday I'll replace that SMV with a custom solution.

**Closed by raiguard** 2020-02-24 17:20 UTC
Labels: support
