### ISSUE TITLE
Issue with DiskMeter

### ISSUE THREAD

**Issue by Marthisdil** [raiguard/ModernGadgets#216] opened 2020-11-06 01:19 UTC
Latest version of the gadget.  Has started throwing tons of these errors:

Formula: Extra operation in key "Hidden" in [MeterDisk10TempString] (ModernGadgets\DisksMeter\DisksMeter.ini)
Formula: Extra operation in key "Hidden" in [MeterDisk10EjectButton_] (ModernGadgets\DisksMeter\DisksMeter.ini)

I have the show eject buttons disabled in the settings.

**Comment by raiguard** [comment] 2020-11-14 00:50
Duplicate of #203.

**Closed by raiguard** 2020-11-14 00:50 UTC
