### ISSUE TITLE
Unable to use the Motherboard ID and Instance.

### ISSUE THREAD

**Issue by lwaite9** [raiguard/ModernGadgets#44] opened 2017-08-05 23:06 UTC
I've read the documentation, and I'm fairly certain I'm doing this correctly, but even when using the HwiNFO Shared memory viewer from it's plugin (not from MG) I still cannot get it to use my motherboard's ID and Instance. Included are my memory dump, GlobalSettings.inc, and HWiFNO.inc

[HWiNFOSharedMemoryViewer.dump.txt](https://github.com/iamanai/ModernGadgets/files/1202734/HWiNFOSharedMemoryViewer.dump.txt)

[GlobalSettings.inc.txt](https://github.com/iamanai/ModernGadgets/files/1202736/GlobalSettings.inc.txt)

[HWiNFO.inc.txt](https://github.com/iamanai/ModernGadgets/files/1202737/HWiNFO.inc.txt)

I will also include a screenshot of the issue.

![ogknj1pltts_i26x6b_wdg](https://user-images.githubusercontent.com/5608236/28999347-15baeb2a-7a11-11e7-8f0b-5fda2bcf4b6a.png)

**Comment by iamanai** [comment] 2017-08-06 14:10
Well, it appears that it's actually working, even though the config tool thinks it's wrong. The fan speed in CPU Meter is correct.

On an unrelated note, do AMD CPUs not have a DTS section? Where does HWiNFO put the temperature sensors for your CPU?

**Comment by raiguard** [comment] 2017-09-26 15:08
So this issue appears to be that the config took thinks it is incorrect, but it actually is. Since I cannot reproduce it, I am closing this issue. Let me know if you discover anything else on this subject.

**Closed by raiguard** 2017-09-26 15:08 UTC
Labels: bug
