### ISSUE TITLE
Ryzen 1950x Core Temps & Voltages not showing up and greyed out in Settings

### ISSUE THREAD

**Issue by XiCynx** [raiguard/ModernGadgets#128] opened 2019-02-03 18:38 UTC
As you can see in the below screenshot, Core Tempuratures and Core Voltages are greyed out.  They do not show up in the graph on the right.  I tried manually going into the CPU Meter Settings .ini and manually changed the check boxes from 1 to 0 and then back to 1 again but no dice. It also seems that Fan Speed, CPU Temp Graph and Thermal Throttling are also greyed out.

Modern Gadgets Version: 1.4.1 - Should I try using a beta version?
HWInfo64 Version: 6.000-3620

https://imgur.com/0vyO3fL.png
https://i.imgur.com/ab36rQg.png
https://i.imgur.com/rD6X7Eo.png

**Comment by raiguard** [comment] 2019-02-03 20:58
They're grayed out because CPU Meter seems to think that HWiNFO is not running... From your drive temperatures issue, it appears that you correctly configured HWiNFO, so I don't know why it would be doing this.

Open the Rainmeter log (right-click on Rainmeter's tray icon and click 'About'), then middle-click CPU Meter and tell me what the log says.

**Comment by XiCynx** [comment] 2019-02-04 03:36
Seems that it just shows that the skin refreshes and that it is.  All of the boxes at the bottom are checked for Error, Warning, Notice and Debug. But no errors are being thrown.  I also posted a screenshot of the Skins Tab as well in case anything in there is of good information.

https://i.imgur.com/DITWHNJ.png
https://i.imgur.com/Mn8nKSW.png

**Comment by raiguard** [comment] 2019-02-04 03:54
I think I know what the problem is. Could you go to the skins tab, and in CPU Meter, find `MeasureHwinfoDetect` and tell me what the values are?

**Comment by raiguard** [comment] 2019-02-05 03:58
Aha! I know how to fix this, it was a mistske on my part. This is happening because your `Core 0 Temperature` sensor is incorrectly configured. I assume that since you have a Ryzen processor, it doesn't have individual core temperature sensors. If this is the case, tie `Core 0 Temperature` to any entry in the list, and it should fix the issue.

Technical Explanation: the HWiNFO detection works by getting the value of the `Core 0 Temperature` sensor, and enabling error code output on the measure. What I meant to do was to have it report that HWiNFO wasn't running if the measure returned the error code saying that. However, I accidentally made it do that if it returned any error code at all. So the fix is to make it behave like I originally intended.

**Comment by XiCynx** [comment] 2019-02-05 04:01
Badabing, Badaboom my man!  Up and running like a charm!  Silly Ryzen and its missing individual core temps, who wouldn't thought they couldn't fit 16 of them on that massive die. Lol

**Comment by raiguard** [comment] 2019-02-05 11:16
Glad it works now! Yes, I did add an option to just display the package temperature for those who have Ryzen processors. You'll have to enable bets updates though, because 1.5 won't be officially released for a while yet. Luckily bets updates are usually pretty stable, so you shouldn't need to worry too much (in fact, most of MG's userbase is on the betas rather than the official releases).

**Comment by raiguard** [comment] 2019-02-05 21:38
Will be fixed in v1.5.0-beta.9.

**Comment by raiguard** [comment] 2019-02-15 03:54
Beta 9 is finally out. Please let me know if this fixes the issue!

**Comment by monkeemunk** [comment] 2019-02-16 00:58
So I'm having this same problem but I'm not quite sure how to as you said "tie `Core 0 Temperature` to any entry in the list". An chance you could elaborate on that cuz I'm stumped.

**Comment by raiguard** [comment] 2019-02-16 03:51
Are you on beta 9?

**Comment by monkeemunk** [comment] 2019-02-16 04:23
Yessir

**Comment by raiguard** [comment] 2019-02-16 17:28
Did you install and configure HWiNFO as per the tutorial? You can find a link to the tutorial in the blue book icon above the "Open Shared Memory Viewer" button in the CPU Meter Settings skin.

**Comment by monkeemunk** [comment] 2019-02-16 19:57
All working now, thanks bud.

**Comment by raiguard** [comment] 2019-02-17 05:09
Well since I am 99.9% sure I fixed this bug, I'm just gonna close this issue now. XiCynx, if this issue is still present, please let me know. :)

**Closed by raiguard** 2019-02-17 05:09 UTC
Labels: bug, support
